### ISSUE TITLE
有微调参数更大模型 或 数据集持续更新、纠错的计划吗？

### ISSUE THREAD

**Issue by shadow01a** [ystemsrx/Qwen2-Boundless#5]
如题

**Comment by ystemsrx** [comment]
是的，后续可能会微调更大的模型。数据集我又整理了一些，[点击这里](https://huggingface.co/datasets/ystemsrx/Toxic-All)查看。

**Comment by shadow01a** [comment]
这数据集确实相当激进，不知道与原有数据集结合后微调的模型表现如何。

**Comment by ystemsrx** [comment]
最近又爬了一些新数据集，可以[在这里](https://huggingface.co/datasets/ystemsrx/Erotic_Literature_Collection)看看
